// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MinimalAPIWithDapper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Lorena",
                            LastName = "Marvin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ramon",
                            LastName = "Von"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jacob",
                            LastName = "Bahringer"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Merle",
                            LastName = "Kreiger"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ed",
                            LastName = "Leannon"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Jenna",
                            LastName = "Ledner"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Tonya",
                            LastName = "Beahan"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "George",
                            LastName = "Witting"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Natasha",
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Beatrice",
                            LastName = "Orn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
